### ISSUE TITLE
sonata02-1

### ISSUE THREAD

**Issue by napulen** [craigsapp/beethoven-piano-sonatas#3]
Some proof-read corrections in this score.

---

On `m54`, the encoding of the voices needs some work:

![image](https://user-images.githubusercontent.com/7258463/111494311-bcb4e700-8714-11eb-82a3-4ce07d7c18dc.png)

![image](https://user-images.githubusercontent.com/7258463/111494280-b6bf0600-8714-11eb-9a53-1827ca38d3ca.png)

---

On `m57`, the `D` on the bass should be `D#`, because it is tied to the previous measure (so also the tie encoding needs to be added for the `D` and `F#`)

![image](https://user-images.githubusercontent.com/7258463/111494445-db1ae280-8714-11eb-8a4c-d6a6ce4485d9.png)

![image](https://user-images.githubusercontent.com/7258463/111494484-e40bb400-8714-11eb-92b8-8a63d38d4fc2.png)

---

On `m134`, the `A` on the bottom should be an `A-`:

![image](https://user-images.githubusercontent.com/7258463/111494612-000f5580-8715-11eb-90b9-f99ad02d07c5.png)

![image](https://user-images.githubusercontent.com/7258463/111494768-22a16e80-8715-11eb-8d1d-991ae028baf6.png)

**Comment by craigsapp** [comment]
Thanks!

Fixed with commits https://github.com/craigsapp/beethoven-piano-sonatas/commit/b41f3aa2ea72d2487cbfb34e8370dbd2ce24c001 and https://github.com/craigsapp/beethoven-piano-sonatas/commit/f1bfd64d29333774bf4864f0eba2ed75c23e15fe.

Measure 54:

<img width="134" alt="Screen Shot 2021-03-17 at 9 43 17 PM" src="https://user-images.githubusercontent.com/3487289/111574541-e9dfb480-8769-11eb-938f-61a8a77be521.png">

New encoding with the proper voicings:

```tsv
=54			=54		=54
*^			*^		*
*	*^		*	*	*
4rf	8rA	[<2D#\	2rff	4re	.
.	[4.F#/	.	.	.	.
[<4A	.	.	.	8re	.
.	.	.	.	8B<	.
*v	*v	*v	*	*	*
*			*v	*v	*
=55			=55		=55
```

Pitch and ties fixed in m57:

<img width="492" alt="Screen Shot 2021-03-17 at 9 48 05 PM" src="https://user-images.githubusercontent.com/3487289/111574856-80ac7100-876a-11eb-9c53-fe263e2542d9.png">

m134 added the flat:

<img width="229" alt="Screen Shot 2021-03-17 at 9 50 07 PM" src="https://user-images.githubusercontent.com/3487289/111574999-c36e4900-876a-11eb-9015-86b0b9a95984.png">
